### ISSUE TITLE
Feature request: Configuration options

### ISSUE THREAD

**Issue by MISMASJETU** [peteward44/ONIMods#3]
Its simple, I already written comment on steam page, but I will repeat it here.

I myself hate cheaty and cheese things in games, but sometimes its nice to have them, I personally like to play ONI relaxed, so I think it would be nice if you could provide configuration options so we could edit the ammount of heat and power needed. I am sure this is a really small thing you could do. Love the mod BTW

**Comment by peteward44** [comment]
Hi this is present in the latest version. Cheers
