### ISSUE TITLE
Wild Planter no longer showing up in build menu

### ISSUE THREAD

**Issue by dpcarr3** [peteward44/ONIMods#5]
just wanted to let you know that the planter is no longer showing up in the build menu since the feb 25th update. Nycidian commented on the steam page with the following which may help:

[Nycidian] Feb 26 @ 8:21am 
It's a common issue with many mods.

[https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-mod-build-items-in-menu-r34127/](https://steamcommunity.com/linkfilter/?url=https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-mod-build-items-in-menu-r34127/)

Answer: "Mods using our supported ModUtil.AddBuildingToPlanScreen to add buildings are unaffected. This mod is not using that method and needs to be updated by the author. "

**Comment by peteward44** [comment]
Thanks for bringing this to my attention, i've just released v4.0.1 to address this. Cheers
