### ISSUE TITLE
New update causes crash when deconstructing wild planter boxen

### ISSUE THREAD

**Issue by maeamian** [peteward44/ONIMods#7]
As of Sweet Dreams update, ordering deconstruction of the wild planter tiles (possibly only on non-home asteroids with Spaced Out DLC) causes a game crash, log attached.
[Player.log](https://github.com/peteward44/ONIMods/files/9848502/Player.log)

**Comment by peteward44** [comment]
Thanks for reporting. I'll take a look when i'm able

**Comment by peteward44** [comment]
Just released 4.0.2 which should fix this. Thankyou
